attributes:
    support_dpdk:
      type: "checkbox"
      weight: 20
      value: false
      label: "support DPDK"
    support_nsh:
      type: "checkbox"
      weight: 20
      value: false
      label: "support NSH"
    support_nsh_dpdk:
      type: "checkbox"
      weight: 20
      value: false
      label: "support NSH & DPDK"
